### What is NumPy?
NumPy is a scientific computing package (library) for python programming language.

Numpy is a powerful Python programming language library to solve numerical problems.

**What is the meaning of NumPy word?**

Num stands for numerical and Py stands for Python programming language.

**Python NumPy library** is especially used for numeric and mathematical calculation like linear algebra, Fourier transform, and random number capabilities using Numpy array.

NumPy supports large data in the form of a **multidimensional array** (vector and matrix).

### How to install Python NumPy Library (package)?

In [1]:
pip install numpy

### How to import NumPy Library in IDE or How to use it?
To use NumPy first import it. For import NumPy, follows below syntax in the python program file.

In [2]:
import numpy as np

• **import:** import keyword imports the NumPy package in the current file.

• **as:**  as is a keyword used to create sort name of NumPy.

• **np:** np is a short name given to NumPy, you can give any name (identifier) instead of it. If we use NumPy name in the program repeatedly so it will consume typing time and energy as well so for that we gave a short name for our convenience.

### How to create one dimensional NumPy array?
To create python NumPy array use array() function and give items of a list.

**Syntax:** numpy.array(object, dtype=None, copy=True, order=’K’, subok=False, ndmin=0)

In [3]:
import numpy as np # import numpy package
one_d_array = np.array([1,2,3,4]) # create 1D array
print(one_d_array) # printing 1d array

[1 2 3 4]


### How to create two dimensional NumPy array?
To create 2D array, give items of lists in list to NumPy array() function.


In [4]:
import numpy as np # impoer numpy package
two_d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # create 1D array
print(two_d_array) #printing 2D array
# In this way, you can create NumPy ndarray

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### How to check the type of ndarray?
The type() function give the type of data.

**Syntax:** type(self, /, *args, **kwargs)

In [5]:
type(one_d_array) # give the type of data present in one_d_array variable

numpy.ndarray

### How to check dimension of NumPy ndarray?
The ndim attribute help to find the dimension of any NumPy array.

**Syntax:** array_name.ndim

In [6]:
one_d_array.ndim # find the dimension of one_d_array

1

### How to check the size of the NumPy array?
The size attribute help to know, how many items present in a ndarray.

**Syntax:** array_name.size

In [7]:
one_d_array.size
# 4 value represent, total 4 item present in the one_d_array.

4

### How to check the shape of ndarray?
The shape attribute help to know the shape of NumPy ndarray. It gives output in the form of a tuple data type. Tuple represents the number of rows and columns. Ex: (rows, columns)

**Syntax:** array_name.shape

In [8]:
two_d_array.shape
# The two_d_array has 3 rows and 3 columns.

(3, 3)

### How to the data type of NumPy ndarray?
The dtype attribute help to know the data type of ndarray.

**Syntax:** array_name.dtype

In [9]:
one_d_array.dtype
# As per the above output one-d_array contain integer type data. This data store in 32 bit format (4 byte).

dtype('int64')

### Create metrics using python NumPy functions
Ones metrics use NumPy ones() function.

**Syntax:** np.ones(shape, dtype=None, order=‘C’)

In [10]:
np.ones((3,3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [11]:
# Syntax: np.zeros(shape, dtype=None, order=‘C’)
np.zeros((3, 3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### Empty metrics use NumPy empty() function.

**Syntax:** np.empty(shape, dtype=None, order=‘C’)

In [12]:
np.empty((2,4))
# By default NumPy empty() function give float64 bit random value. According to your requirement change dtype.

array([[4.04851739e-315, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

### Create NumPy 1D array using arange() function

**Syntax:** np.arange([start,] stop[, step,], dtype=None)

In [13]:
arr = np.arange(1,13)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


### Create NumPy 1D array using linspace() function

Return evenly spaced numbers over a specified interval.

**Syntax:** np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0,)

In [14]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

### Convert 1D array to multidimensional array using reshape() function

**Syntax:** np.reshape(a, newshape, order=‘C’)

In [15]:
arr_reshape = np.reshape(arr, (3,4))
print(arr_reshape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Convert multidimensional array in one dimensional

To convert multidimensional array into 1D use ravel() or flatten() function.

**Syntax:** np.ravel(array_name, order=‘C’)  or  array_name.ravel(order=‘C’)

array_name.flatten(order=‘C’)

In [16]:
arr_reshape.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### Transpose metrics

**Syntax:** np.transpose(array_name, axes=None)  or

array_name.T

### 1. What does transpose mean?

 Transpose = swap rows with columns

If your array is:

Rows → Columns


After transpose:

Columns → Rows

### 2. np.transpose(array_name, axes=None)

• Syntax

np.transpose(array_name, axes=None)

• Parameters
| Parameter   | Meaning |
|------------|---------|
| `array_name` | NumPy array you want to transpose |
| `axes`       | Order of axes (used for multi-dimensional arrays) |

If axes=None → NumPy automatically reverses the dimensions.

In [17]:
# Example
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [18]:
transposed = np.transpose(arr)
print(transposed)

[[1 4]
 [2 5]
 [3 6]]


### Explanation

Rows became columns

Shape changed from (2,3) → (3,2)

### 3.array_name.T (Shortcut Way)

• Syntax

array_name.T

This is just a short and cleaner way to do the same thing.

In [19]:
# Example
print(arr.T) # Using .T
# Same result as np.transpose(arr)


[[1 4]
 [2 5]
 [3 6]]


In [20]:
# 1D Array Case
arr1d = np.array([1, 2, 3, 4])
print(arr1d.T)

[1 2 3 4]


### Why no change?

• 1D array has only one axis

• Nothing to swap

 To transpose properly, reshape first:

In [21]:
arr1d = arr1d.reshape(1, 4)
print(arr1d.T)

[[1]
 [2]
 [3]
 [4]]


In [22]:
# Using axes (Advanced – for 3D arrays)
# Example
arr3d = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])

print(arr3d.shape)

(2, 2, 2)


In [23]:
# Transpose with axes:
trans = np.transpose(arr3d, axes=(1, 0, 2))
print(trans.shape)

(2, 2, 2)


### # Meaning of axes
(1, 0, 2) → swap axis 0 and 1, keep axis 2 same