### What is NumPy Array Split?

Splitting = divide one array into multiple smaller arrays

Core function:

np.split(array, indices_or_sections, axis=0)

### 1. np.split() – Core Function

### Syntax

np.split(ary, indices_or_sections, axis=0)

### 2. Parameters Explained (One by One)
ary (required)

• The NumPy array you want to split

indices_or_sections (required)

Two meanings depending on type:

✔ Integer value

• Number of equal parts

• Array length must be divisible

✔ List / tuple

Index positions where splits occur

axis (default = 0)

• Direction of split

• 0 → split rows

• 1 → split columns

### 3. 1D Array Splitting
Example 1: Split into equal parts

In [15]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60])
result = np.split(arr, 3)
print(result)
# 6 elements ÷ 3 = 2 per chunk

[array([10, 20]), array([30, 40]), array([50, 60])]


In [16]:
# Example 2: Invalid split
np.split(arr, 4)
# Error: cannot divide equally

ValueError: array split does not result in an equal division

In [ ]:
# Example 3: Using indices
data = np.array([[10, 20],
                 [30, 40],
                 [50, 60],
                 [70, 80],
                 [90, 100]])  # Added more rows to allow index 4

splits = np.split(data, [2, 4])
for i, part in enumerate(splits):
    print(f"Split {i}:\n{part}\n")

# Splits at index 2 and 4

# 2D Array Splitting
Create array

In [ ]:
arr2d = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12],
    [13,14, 15,16]
])
arr2d

In [ ]:
# Example 4: Split rows (axis=0)
np.split(arr2d, 2, axis=0)

In [17]:
# Example 5: Split columns (axis=1)
np.split(arr2d, 2, axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

### 5. np.array_split()
Unlike np.split(), this allows unequal splits

In [18]:
np.array_split(arr, 4)
# No error

[array([10, 20]), array([30, 40]), array([50]), array([60])]

### 6. Shortcut Split Functions

In [19]:
#  np.vsplit() – Vertical split (rows)
np.vsplit(arr2d, 2)
# Same as axis=0

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [20]:
# np.hsplit() – Horizontal split (columns)
np.hsplit(arr2d, 2)
# Same as axis=1

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

### 7. Real-World ML Example
Train/Test Split (without sklearn)

In [21]:
data = np.arange(100)
train, test = np.split(data, [80])
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

### What's Happening in above output
• np.arange(100) creates an array from 0 to 99 → total 100 elements.

• np.split(data, [80]) splits the array at index 80:

  • train → first 80 elements → data[0:80]

  • test → remaining 20 elements → data[80:100]

• Printing data shows the full array from 0 to 99, which matches the output.

### 8. Comparison Table
| Function         | Equal Split Required | Axis Control      |
|------------------|----------------------|-------------------|
| np.split()       | Yes                  | Yes               |
| np.array_split() | No                   | Yes               |
| np.vsplit()      | Yes                  | Rows only         |
| np.hsplit()      | Yes                  | Columns only      |

### Key Points
• np.split() fails if not divisible

• indices_or_sections can be int or list

• array_split() is safer

• Axis controls direction

• Output is list of arrays

### Final Summmary
• Used to divide arrays

• Core function: np.split()

• Axis defines row/column split

• array_split() avoids errors

• Very common in ML pipelines