### What is NumPy Array Concatenation?

Concatenation = joining two or more arrays together

NumPy provides multiple ways, but the core function is:

np.concatenate((arr1, arr2, ...), axis=0)

### 1. np.concatenate() – Core Function

### Syntax

np.concatenate((a1, a2, ...), axis=0, out=None, dtype=None,
casting="same_kind")

### 2. Parameters Explained (One by One)
(a1, a2, ...) (required)

Tuple of arrays to join

Arrays must have same shape, except along the concatenation axis

(a1, a2)

### axis (default = 0)

• Direction of joining

• 0 → row-wise (vertical)

• 1 → column-wise (horizontal)

### out (optional)

• Pre-allocated output array

• Rarely used (advanced memory optimization)

### dtype (optional)

• Force output data type

### casting (optional)

• Controls how dtype conversion happens

• Common value: "same_kind"

### 3. Simple 1D Array Concatenation

In [23]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.concatenate((a, b))
print(result)
# Axis doesn’t matter for 1D arrays.

[1 2 3 4 5 6]


### 4. 2D Array Concatenation (Most Important 🔥)
Create arrays

In [24]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])
print(a,b)

[[1 2]
 [3 4]] [[5 6]
 [7 8]]


In [25]:
# Axis = 0 (Row-wise)
np.concatenate((a, b), axis=0)
# Rows increased

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [26]:
# Axis = 1 (Column-wise)
np.concatenate((a, b), axis=1)
# Columns increased

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### 5. Shape Rules (VERY IMPORTANT)
This will FAIL:

In [27]:
a = np.array([[1, 2]])
b = np.array([[3, 4], [5, 6]])

np.concatenate((a, b), axis=0)
# Because shapes must match except axis

array([[1, 2],
       [3, 4],
       [5, 6]])

### 6. out Parameter Example

In [28]:
# Option 1: Remove out
result = np.concatenate((a, b), axis=0)
print(result)

[[1 2]
 [3 4]
 [5 6]]


In [29]:
# Option 2: Use np.vstack() or np.hstack() if shapes align
result = np.vstack((a, b))  # for vertical stacking
result

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
# Option 3: Check shapes before concatenation
print(a.shape, b.shape)

(1, 2) (2, 2)


### 7. dtype Parameter Example

In [31]:
np.concatenate((a, b), dtype=float)
# Forces output to float

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

### 8. casting Parameter

In [32]:
np.concatenate((a, b), casting="same_kind")
# Controls how NumPy allows type casting

array([[1, 2],
       [3, 4],
       [5, 6]])

### 9. Shortcut Functions (Built on concatenate)
np.vstack() – Vertical stack

In [33]:
np.vstack((a, b))
# Same as axis=0

array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
# np.hstack() – Horizontal stack
a = np.array([[1, 2]])        # shape (1, 2)
b = np.array([[3, 4]])        # shape (1, 2)
np.hstack((a, b))             # works → [[1, 2, 3, 4]]
# Same as axis=1

array([[1, 2, 3, 4]])

In [35]:
# np.column_stack()
np.column_stack((a[:, 0], b[:, 0]))
# Stacks 1D arrays as columns

array([[1, 3]])

In [36]:
# np.row_stack()
np.row_stack((a, b))
# Alias of vstack

/tmp/ipython-input-2001237120.py:2: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[1, 2],
       [3, 4]])

### 10. Real-World ML Example

In [37]:
# Merge features
X1 = np.array([[1, 2], [3, 4]])
X2 = np.array([[5], [6]])

X = np.concatenate((X1, X2), axis=1)
# Add new feature column
X

array([[1, 2, 5],
       [3, 4, 6]])

### Quick Comparison Table
| Function      | Axis        | Use Case               |
|---------------|-------------|------------------------|
| concatenate   | Any         | Full control           |
| vstack        | 0           | Stack rows             |
| hstack        | 1           | Stack columns          |
| column_stack  | Columns     | Feature engineering    |

### Final Summary

• np.concatenate() is the core function

• Arrays must match shapes (except axis)

• axis=0 → rows, axis=1 → columns

• vstack / hstack are shortcuts

• Widely used in ML & data preprocessing