### What is NumPy Array Slicing?

Slicing = extracting a part of an array

### General Syntax
array[start : stop : step]

| Part  | Meaning                        |
|-------|--------------------------------|
| start | Index to begin (included)      |
| stop  | Index to stop (excluded)       |
| step  | Jump size                      |

If we skip any value, NumPy uses defaults.

### 1D Array Slicing (Basic)
Example 1: Simple Slice

In [11]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])
print(arr[1:4])
# Explanation:
# Starts at index 1
# Stops before index 4

[20 30 40]


In [12]:
# Example 2: From start / till end
print(arr[:3])     # from start
print(arr[3:])     # till end

[10 20 30]
[40 50 60]


In [13]:
# Example 3: Using step
print(arr[::2])
# Takes every 2nd element


[10 30 50]


In [14]:
# Example 4: Negative slicing
print(arr[-4:-1])
# Counts from the end

[30 40 50]


### 2D Array Slicing
Create a 2D array

In [15]:
arr2d = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12]
])
print(arr2d[0:2])

[[1 2 3 4]
 [5 6 7 8]]


In [16]:
# Example 5: Slice columns
print(arr2d[:, 1:3])
# Explanation:
# : → all rows
# 1:3 → column index 1 and 2

[[ 2  3]
 [ 6  7]
 [10 11]]


In [17]:
# Example 6: Slice rows & columns together
print(arr2d[1:3, 0:2])

[[ 5  6]
 [ 9 10]]


In [18]:
# Using Step in 2D Arrays
print(arr2d[::2, ::2])
# Skips every second row & column

[[ 1  3]
 [ 9 11]]


In [19]:
# Modifying Values Using Slicing
arr2d[:, 2] = 99
print(arr2d)
# Slicing returns a view, not a copy

[[ 1  2 99  4]
 [ 5  6 99  8]
 [ 9 10 99 12]]


### View vs Copy

View = shares data with original array

Copy = separate data (original stays safe)

### 1.Original Array

In [20]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


### VIEW Example (Slicing)

In [21]:
view_arr = arr[1:4]   # slicing → VIEW
print(view_arr)

[20 30 40]


In [22]:
# Modify the view
view_arr[0] = 999
print(view_arr)
print(arr)
# mportant:
# Changing view_arr also changed arr !
# Because view shares memory

[999  30  40]
[ 10 999  30  40  50]


### COPY Example

In [23]:
copy_arr = arr[1:4].copy()   # force COPY
print(copy_arr)

[999  30  40]


In [24]:
# Modify the copy
copy_arr[0] = 777
print(copy_arr)
print(arr)
# Original array did NOT change ✔
# Because copy has its own memory

[777  30  40]
[ 10 999  30  40  50]


### Visual Memory Idea

### View
arr      → [10, 999, 30, 40, 50]

view_arr →     ↑ same memory

### Copy

arr      → [10, 999, 30, 40, 50]

copy_arr → [777, 30, 40]  (separate)

In [25]:
# Quick Check
view_arr.base is arr
# True → it’s a view

True

In [26]:
copy_arr.base is arr
# False → it’s a copy

False

### When to Use What?
 Situation                    | Use     |
|------------------------------|---------|
| Performance & memory efficiency | View    |
| Safe data manipulation       | Copy    |
| ML preprocessing             | Copy    |
| Quick filtering              | View    |