### What is NumPy Random Sampling?

Random sampling = generating random numbers from different distributions

All random functions live in:

np.random


(Modern NumPy uses np.random.default_rng() — I’ll explain both styles)

### np.random.rand() – Uniform (0 to 1)

###Syntax

np.random.rand(d0, d1, ..., dn)

### Parameters

| Parameter | Meaning                    |
|-----------|----------------------------|
| d0, d1, … | Shape of output array      |

In [1]:
# Example
import numpy as np
np.random.rand(3)
# values are uniformly distributed between 0 and 1

array([0.15246139, 0.05306585, 0.93593118])

### 2. np.random.randn() – Normal Distribution (Mean=0, Std=1)

**Syntax**

np.random.randn(d0, d1, ..., dn)

In [2]:
# Example
np.random.randn(5)
# Can generate negative & positive values

array([-1.16779553, -0.63074103,  0.78324182,  1.21116147,  0.05777054])

### 3. np.random.randint() – Random Integers

**Syntax**

np.random.randint(low, high=None, size=None, dtype=int)

### Parameters Explained

| Parameter | Meaning                          |
|-----------|----------------------------------|
| low       | Minimum value (inclusive)        |
| high      | Maximum value (exclusive)        |
| size      | Output shape                     |
| dtype     | Data type                        |

In [3]:
# Examples
np.random.randint(1, 10)

3

In [4]:
np.random.randint(1, 10, size=5)

array([6, 3, 7, 4, 5])

In [5]:
np.random.randint(1, 10, size=(2,3))

array([[7, 9, 2],
       [5, 8, 3]])

### 4. np.random.choice() – Random Sampling from Data

**Syntax**

np.random.choice(a, size=None, replace=True, p=None)

### Parameters

| Parameter | Meaning                       |
|-----------|-------------------------------|
| a         | Array or integer              |
| size      | Output shape                  |
| replace   | Allow repetition or not       |
| p         | Probability of each element   |

In [6]:
# Example 1: Simple sampling
np.random.choice([10, 20, 30, 40])

np.int64(20)

In [7]:
# Example 2: Multiple samples
np.random.choice([10, 20, 30, 40], size=3)

array([30, 20, 30])

In [8]:
# Example 3: No repetition
np.random.choice([10, 20, 30, 40], size=3, replace=False)

array([30, 40, 20])

In [9]:
# Example 4: Weighted sampling
np.random.choice([1, 2, 3], size=5, p=[0.1, 0.7, 0.2])
# Value 2 appears more often

array([3, 2, 2, 2, 2])

### 5.np.random.uniform() – Custom Range

**Syntax**

np.random.uniform(low=0.0, high=1.0, size=None)

In [10]:
# Example
np.random.uniform(10, 20, size=5)

array([10.50975851, 11.22725683, 11.48926323, 17.77059453, 14.07048765])

### 6. np.random.normal() – Normal Distribution (Custom)

**Syntax**

np.random.normal(loc=0.0, scale=1.0, size=None)

### Parameters

| Parameter | Meaning                |
|-----------|------------------------|
| loc       | Mean                   |
| scale     | Standard deviation     |
| size      | Output shape           |

In [11]:
# Example
np.random.normal(loc=50, scale=5, size=5)

array([46.39879843, 60.30181096, 45.1446059 , 47.87966181, 56.09854837])

### 7. np.random.shuffle() – Shuffle Array (In-place)

**Syntax**

np.random.shuffle(arr)

In [12]:
# Example
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)
# Original array is modified

[3 5 2 1 4]


### 8. np.random.permutation() – Shuffled Copy

In [13]:
np.random.permutation([1, 2, 3, 4, 5])
# Returns new array

array([4, 2, 3, 1, 5])

### np.random.seed() – Reproducibility

In [14]:
np.random.seed(42)
np.random.rand(3)
# Same output every run (important for ML experiments)

array([0.37454012, 0.95071431, 0.73199394])

### 10. Modern Way (Recommended)

In [15]:
rng = np.random.default_rng(42)
rng.integers(1, 10, size=5)
rng.normal(0, 1, size=5)
rng.choice([10, 20, 30], size=2)
# Better randomness & thread-safe

array([30, 20])

### Quick Comparison Table

| Function     | Use Case                |
|--------------|-------------------------|
| rand         | Uniform (0–1)           |
| randn        | Standard normal         |
| randint      | Random integers         |
| choice       | Sampling from data      |
| uniform      | Custom range            |
| normal       | Gaussian values         |
| shuffle      | In-place shuffle        |
| permutation  | Shuffled copy           |

### Final Summary

• NumPy supports many random distributions

• choice() is key for sampling datasets

• seed() ensures reproducibility

• Use default_rng() for modern code

• Widely used in ML, simulations & testing